<?xml version="1.0"?>
<package format="3">
  <name>bootcamp_basics</name>
  <version>0.0.1</version>
  <description>ROS2 basics examples: pub/sub, service, turtlesim</description>

  <maintainer email="bootcamp@example.com">bootcamp</maintainer>
  <license>Apache-2.0</license>

  <!-- IMPORTANT for Python packages -->
  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>example_interfaces</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>turtlesim</exec_depend>
  <exec_depend>bootcamp_interfaces</exec_depend>


  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
